<?php
/*
Plugin Name: Tarif Cargo Plugin
Description: Plugin untuk mengelola dan cek tarif cargo dengan menu admin dan shortcode frontend.
Version: 1.0
Author: Generated by Ferry
*/

// Exit if accessed directly
if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

// Define plugin URL and path
define( 'TARIF_CARGO_PLUGIN_URL', plugin_dir_url( __FILE__ ) );
define( 'TARIF_CARGO_PLUGIN_PATH', plugin_dir_path( __FILE__ ) );

// Enqueue admin scripts and styles
function tarif_cargo_admin_assets($hook) {
    // Load assets only on our plugin admin page
    if ( $hook !== 'toplevel_page_tarif-cargo' ) {
        return;
    }
    // Enqueue Font Awesome CSS for admin icons
    wp_enqueue_style( 'font-awesome', 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css', array(), '6.5.0' );
    wp_enqueue_style( 'tarif-cargo-admin-style', TARIF_CARGO_PLUGIN_URL . 'css/style.css', array(), '1.0' );
    wp_enqueue_script( 'tarif-cargo-admin-script', TARIF_CARGO_PLUGIN_URL . 'js/admin.js', array('jquery'), '1.0', true );
}
add_action( 'admin_enqueue_scripts', 'tarif_cargo_admin_assets' );

// Enqueue frontend scripts and styles
function tarif_cargo_frontend_assets() {
    wp_enqueue_style( 'tarif-cargo-frontend-style', TARIF_CARGO_PLUGIN_URL . 'css/style.css', array(), '1.0' );
    wp_enqueue_script( 'tarif-cargo-frontend-script', TARIF_CARGO_PLUGIN_URL . 'js/frontend.js', array('jquery'), '1.0', true );
    wp_localize_script( 'tarif-cargo-frontend-script', 'ajaxurl', admin_url( 'admin-ajax.php' ) );
}
add_action( 'wp_enqueue_scripts', 'tarif_cargo_frontend_assets' );

// Admin menu page callback
function tarif_cargo_admin_page() {
    ?>
    <div class="tarif-cargo-plugin wrap">
        <h1>Kelola Data Tarif Cargo</h1>
        <div id="container-manage-data" class="tarif-cargo-container">
            <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 10px;">
                <button id="btnOpenAddEntryModal" class="tarif-cargo-btn">Tambah Data Baru</button>
                <input type="text" id="searchInput" placeholder="Cari kota..." style="padding: 6px 10px; border: 1.5px solid #cbd5e1; border-radius: 6px; font-size: 1rem; width: 200px;" aria-label="Pencarian data tarif cargo" />
            </div>

            <table aria-label="Tabel rekap data tarif lengkap" class="tarif-cargo-table">
                <thead>
                    <tr>
                        <th>No</th>
                        <th><button type="button" class="sort-btn tarif-cargo-sort-btn" data-sort="kotaAwal">Kota Awal</button></th>
                        <th><button type="button" class="sort-btn tarif-cargo-sort-btn" data-sort="kotaTujuan">Kota Tujuan</button></th>
                        <th><button type="button" class="sort-btn tarif-cargo-sort-btn" data-sort="layanan">Layanan</button></th>
                        <th><button type="button" class="sort-btn tarif-cargo-sort-btn" data-sort="biaya">Biaya (Rp/kg)</button></th>
                        <th><button type="button" class="sort-btn tarif-cargo-sort-btn" data-sort="estimasi">Estimasi</button></th>
                        <th>Aksi</th>
                    </tr>
                </thead>
                <tbody id="tableBodyEntries" class="tarif-cargo-table-body">
                    <!-- Baris data akan muncul disini -->
                </tbody>
            </table>
            <div id="paginationContainer" style="margin-top: 10px; text-align: center;"></div>
            <div id="messageManageData" class="tarif-cargo-message"></div>
        </div>

        <!-- Modal: Tambah/Edit Entry Data Tarif -->
        <div class="modal tarif-cargo-modal" id="modalAddEditEntry" role="dialog" aria-modal="true" aria-labelledby="modalAddEditEntryTitle" tabindex="-1">
            <div class="modal-content tarif-cargo-modal-content">
                <button class="close-btn tarif-cargo-close-btn" aria-label="Tutup" id="closeAddEditEntry">&times;</button>
                <div class="modal-header tarif-cargo-modal-header" id="modalAddEditEntryTitle">Tambah Data Tarif</div>

                <label for="inputModalKotaAwal" class="tarif-cargo-label">Kota Awal</label>
                <input type="text" id="inputModalKotaAwal" class="tarif-cargo-input" placeholder="Masukkan kota awal" autocomplete="off" aria-autocomplete="list" aria-controls="modalListKotaAwal" aria-expanded="false" aria-haspopup="listbox" role="combobox" aria-activedescendant="" />
                <div id="modalListKotaAwal" class="autocomplete-list tarif-cargo-autocomplete-list" role="listbox"></div>

                <label for="inputModalKotaTujuan" class="tarif-cargo-label">Kota Tujuan</label>
                <input type="text" id="inputModalKotaTujuan" class="tarif-cargo-input" placeholder="Masukkan kota tujuan" autocomplete="off" aria-autocomplete="list" aria-controls="modalListKotaTujuan" aria-expanded="false" aria-haspopup="listbox" role="combobox" aria-activedescendant="" />
                <div id="modalListTujuan" class="autocomplete-list tarif-cargo-autocomplete-list" role="listbox"></div>

                <label for="selectModalLayanan" class="tarif-cargo-label">Layanan</label>
                <select id="selectModalLayanan" class="tarif-cargo-select">
                    <option value="port">Port</option>
                    <option value="door">Door</option>
                </select>

                <label for="inputModalBiaya" class="tarif-cargo-label">Biaya per Kg (Rp)</label>
                <input type="number" id="inputModalBiaya" class="tarif-cargo-input" min="0" placeholder="Misal: 25000" />

                <label for="inputModalEstimasi" class="tarif-cargo-label">Estimasi Waktu Pengiriman (isi angka, misal 1-4)</label>
                <input type="text" id="inputModalEstimasi" class="tarif-cargo-input" placeholder="Misal: 1-4" />

                <div id="messageModalAddEdit" class="tarif-cargo-message"></div>
<div class="modal-footer tarif-cargo-modal-footer">
    <button id="btnSaveEntry" class="btn-save tarif-cargo-btn">Simpan</button>
    <button class="btn-cancel" id="btnCancelEntry">Batal</button>
</div>
            </div>
        </div>
    </div>
    <?php
}

// Register admin menu
function tarif_cargo_admin_menu() {
    add_menu_page(
        'Tarif Cargo',
        'Tarif Cargo',
        'manage_options',
        'tarif-cargo',
        'tarif_cargo_admin_page',
        'dashicons-admin-site',
        6
    );
}
add_action( 'admin_menu', 'tarif_cargo_admin_menu' );

// Frontend shortcode callback
function tarif_cargo_frontend_shortcode() {
    ob_start();
    ?>
    <div class="tarif-cargo-plugin container" id="container-cek-tarif">
        <h2 class="tarif-cargo-title">Cek Tarif Cargo</h2>
        <label for="inputAsalCek" class="tarif-cargo-label">Kota Awal</label>
        <div class="autocomplete-wrapper tarif-cargo-autocomplete-wrapper">
            <input type="text" id="inputAsalCek" class="tarif-cargo-input" placeholder="Cari kota asal..." autocomplete="off" aria-autocomplete="list" aria-controls="listAsal" aria-expanded="false" aria-haspopup="listbox" role="combobox" aria-activedescendant="" />
            <div id="listAsal" class="autocomplete-list tarif-cargo-autocomplete-list" role="listbox" aria-label="Pilihan kota asal"></div>
        </div>

        <label for="inputTujuanCek" class="tarif-cargo-label">Kota Tujuan</label>
        <div class="autocomplete-wrapper tarif-cargo-autocomplete-wrapper">
            <input type="text" id="inputTujuanCek" class="tarif-cargo-input" placeholder="Cari kota tujuan..." autocomplete="off" aria-autocomplete="list" aria-controls="listTujuan" aria-expanded="false" aria-haspopup="listbox" role="combobox" aria-activedescendant="" />
            <div id="listTujuan" class="autocomplete-list tarif-cargo-autocomplete-list" role="listbox" aria-label="Pilihan kota tujuan"></div>
        </div>

        <label for="selectLayananCek" class="tarif-cargo-label">Layanan</label>
        <select id="selectLayananCek" class="tarif-cargo-select">
            <option value="port">Port</option>
            <option value="door">Door</option>
        </select>

        <label for="inputBerat" class="tarif-cargo-label">Masukkan Berat Barang (Kg)
    <span class="weight-note">Minimal 10 Kg</span>
</label>
<input type="number" id="inputBerat" class="tarif-cargo-input" min="0" placeholder="Misal: 12" step="0.1" />

        <button id="btnHitung" class="tarif-cargo-btn">Lihat Tarif</button>
        <button id="btnResetCekTarif" type="button" class="tarif-cargo-btn-cancel">Reset</button>
        <div id="outputCekTarif" class="tarif-cargo-output"></div>
    </div>
    <?php
    return ob_get_clean();
}
add_shortcode( 'tarif_cargo_user', 'tarif_cargo_frontend_shortcode' );

// Register activation hook for creating database table
require_once TARIF_CARGO_PLUGIN_PATH . 'includes/api.php';
register_activation_hook( __FILE__, 'tarif_cargo_create_table' );
?>